/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Aug 6, 2011, 9:58:33 AM
 */
package chatclient;

import java.io.BufferedReader;
import java.io.FileReader;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Nagendra
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPing = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnRegistration = new javax.swing.JButton();
        btnChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText(" Blood Donation : Save Life");

        btnPing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPing.setText("Ping Server");
        btnPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPingActionPerformed(evt);
            }
        });

        btnInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInfo.setText("Edit Server Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnRegistration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistration.setText("Registration");
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });

        btnChat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChat.setText("Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnRegistration)
                            .addComponent(btnPing)
                            .addComponent(btnChat)
                            .addComponent(btnInfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnPing)
                .addGap(26, 26, 26)
                .addComponent(btnInfo)
                .addGap(33, 33, 33)
                .addComponent(btnRegistration)
                .addGap(34, 34, 34)
                .addComponent(btnChat)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        ServerInfoFrame f = new ServerInfoFrame();
        f.setLocation(UtilityFunctions.getCenter(f));
        f.setParent(this);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPingActionPerformed
        Thread t = new Thread() {
            public void run() {
                try {
                    FileReader fr = new FileReader("ServerInfo.txt");
                    BufferedReader br = new BufferedReader(fr);
                    String ip = br.readLine();
                    String port = br.readLine();
                    br.close();
                    Socket s = new Socket(ip, Integer.parseInt(port));
                    MySocket ms = new MySocket(s);
                    ms.println("0000");
                    String str = ms.readLine();
                    if (str.equals("0000")) {
                        JOptionPane.showMessageDialog(MainFrame.this, "Server Available");
                        ms.close();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(MainFrame.this, "Server Not Available \n"+e);
                }
            }
        };
        t.start();
    }//GEN-LAST:event_btnPingActionPerformed

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        RegistrationFrame f = new RegistrationFrame();
        f.setLocation(UtilityFunctions.getCenter(f));
        f.setParent(this);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrationActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        LoginFrame f = new LoginFrame();
        f.setLocation(UtilityFunctions.getCenter(f));
        f.setParent(this);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnPing;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
